- name: Docker build and push
  hosts: local  # Replace with your actual host or group
  become: yes  # Run tasks with sudo

  tasks:
    # Add Kubernetes GPG key first
    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/k8s.gpg

    # Update apt cache after adding the key
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    # Docker build
    - name: Build Docker image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: Tag image
      command: docker tag petstore:latest niklearn1414/petstore:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: niklearn1414
        password: Nikhil@4626

    - name: Push image
      command: docker push niklearn1414/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 niklearn1414/petstore:latest
